### PR TITLE
fix: remove time of day and tz info properly

### LINKED ISSUE #82: BUG: TypeError when replacing TZ info
Getting an TypeError when trying to run evergreen: 

Traceback (most recent call last):
  File "/action/workspace/evergreen.py", line 349, in <module>
    main()  # pragma: no cover
    ^^^^^^
  File "/action/workspace/evergreen.py", line 79, in main
    if created_after_date and repo.created_at.replace(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: str.replace() takes no keyword arguments

cc/ @MorganPattersonSignet since this is a code change you authored previously.

### PR DESCRIPTION
**Pull request by zkoppert**
# Pull Request

## Proposed Changes

fixes #82 

### Author/Contributor

- [x] If documentation is needed for this change, has that been included in this pull request
- [x] run `make lint` and fix any issues that you have introduced
- [x] run `make test` and ensure you have test coverage for the lines you are introducing

### Reviewer

- [x] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, or `breaking`

### CODE REVIEW

**Comment by zkoppert** [comment]
@jmeridth Can add a test here if you are up for it and merge them together.

**Review by jmeridth — APPROVED** [review]
LGTM. If we need to deploy now I'm good. Can add test later tonight when back at keyboard.

**Comment by jmeridth** [comment]
@zkoppert I pushed up tests.  I need to debug some more.  The `repo.created_at` should not be a string from the `github3.py` library.

**Comment by jmeridth** [comment]
Have confirmed locally, the `repo.created_at` variable is a string. 😕 

Looking at a couple more things and then will open this up for review and merge.

**Comment by jmeridth** [comment]
repo.created_at is of type `github3.repos.repo.ShortRepository` which
seems to have a created_at attribute of type string

`github3.repos.repo.Repository` has a parsed created_at type
of `datetime.datetime` object but that is not what we get back
in collections

**Pull request merged**
