### PR TITLE
Batching

### PR DESCRIPTION
**Pull request by gbrindisi**
# Pull Request
This pull request implement a configuration to enable batching the maximum amount of eligible repositories in scope for every Evergreen run.

## Proposed Changes
Add a config variable that is compared to the `eligible_repositories` counter and breaks the repositories loop when the batch value is met.

### Author/Contributor

- [x] If documentation is needed for this change, has that been included in this pull request
- [x] run `make lint` and fix any issues that you have introduced
- [x] run `make test` and ensure you have test coverage for the lines you are introducing

### Reviewer

- [x] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, or `breaking`

### CODE REVIEW

**Comment by zkoppert** [comment]
Hey @gbrindisi ! Thanks for opening up this pull request. Can you help me understand the use case for limiting the number of eligible repos to a max count? Is this for making sure the workflow doesn't take too long?

**Comment by zkoppert** [comment]
Sounds great! Thanks for clarifying. 

Let me know if you'd like support on resolving the ci failures.

**Comment by gbrindisi** [comment]
@zkoppert hey Zack yes please I could use some help. 
Locally I run `make test` and `make lint` and it passes alright, I am not very familiar with mypy

**Comment by zkoppert** [comment]
I'm getting failing results locally for make test. 3 test failures.

```
FAILED test_env.py::TestEnv::test_get_env_vars_with_batch_size - AssertionError: Tuples differ: ('my_[251 chars]ndabot.yaml', None, False, [...
FAILED test_env.py::TestEnv::test_get_env_vars_with_no_batch_size - AssertionError: Tuples differ: ('my_[254 chars]bot.yaml', None, False, ['pr...
FAILED test_env.py::TestEnv::test_get_env_vars_with_repos_exempt_ecosystems - AssertionError: Tuples differ: ('my_[271 chars]False, ['private', 'public']...
```

I will take a look at the linter fixes first and come back to these.

**Review by zkoppert — APPROVED** [review]
Super minor changes to pass the checks! 😅 I'll cut a release shortly after merging.

Thank @gbrindisi for this awesome addition of batching!

**Comment by gbrindisi** [comment]
thanks @zkoppert !

**Pull request merged**
