### PR TITLE
Filter repositories in scope by their visibility

### PR DESCRIPTION
**Pull request by gbrindisi**
# Pull Request
Filter repositories in scope by their visibility

## Proposed Changes
This PR add a configuration option to control the scope of evergreen based on the target repositories visibility. 

By default all repositories are in scope, but if users desire to limit evergreen to only public repositories they now can do so by setting `FILTER_VISIBILITY` to `public`.
If they want to target private and internal repositories they can set it to `private,internal` and so on.

### Author/Contributor

- [x] If documentation is needed for this change, has that been included in this pull request
- [x] run `make lint` and fix any issues that you have introduced
- [x] run `make test` and ensure you have test coverage for the lines you are introducing

### Reviewer

- [x] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, or `breaking`

### CODE REVIEW

**Comment by zkoppert** [comment]
Looks like there are some conflicts on this one. Would you be able to take a look at resolving them @gbrindisi ?

**Comment by gbrindisi** [comment]
@zkoppert done, tests are ok and I run it locally and works as expected.

**Review by zkoppert — APPROVED** [review]
Great feature! Thanks for contributing!

**Comment by gbrindisi** [comment]
@zkoppert sorry for the confusion, I tested without noticing that I had the env variable set in my environment.

I reworked the code a bit to make it more testable.

**Comment by gbrindisi** [comment]
Shouldn't jscpd ignore all test files? 
https://github.com/github/evergreen/blob/874f794ad2daebbb6a2bef202fd13e3216f85a90/.github/linters/.jscpd.json#L4

It seems that the `ignore` directive [expect a glob pattern](https://www.npmjs.com/package/jscpd#ignore). As it is configured now with `test*` maybe is not catching the test files because jscpd is targeted with the abs path towards `/github/workspace/*`?:
```
024-02-29 18:16:16 [INFO]   File:[/github/workspace/test_env.py]
```

This config might work?
```
{
  "threshold": 25,
  "ignore": [
    "/github/workspace/test*"
  ],
  "absolute": true
}
```

**Comment by gbrindisi** [comment]
@zkoppert ouch this closed automatically, take a look please 🙏

**Pull request merged**
